apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.2'
          ports:
            - containerPort: 9200
      initContainers:
        - name: init-myservice
          image: 'busybox'
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
              
