apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    name: es
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: elasticsearch
  type: ClusterIP
