apiVersion: v1
kind: Service
metadata:
  name: foodtruck-web
  labels:
    name: foodtruck-web
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: foodtrucks-web
  type: LoadBalancer
